apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-deployment
  labels:
    app: blockchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain
  template:
    metadata:
      labels:
        app: blockchain
    spec:
      containers:
      - name: blockchain
        image: blockchain-service:latest
        ports:
        - containerPort: 8545
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
spec:
  selector:
    app: blockchain
  ports:
  - protocol: TCP
    port: 8545
    targetPort: 8545
  type: ClusterIP
