apiVersion: v1
kind: Namespace
metadata:
  name: cybersecurity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: cybersecurity
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: cybersecurity-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: cybersecurity
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: cybersecurity-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "sqlite:///cybersecurity.db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-deployment
  namespace: cybersecurity
  labels:
    app: blockchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain
  template:
    metadata:
      labels:
        app: blockchain
    spec:
      containers:
      - name: blockchain
        image: blockchain-service:latest
        ports:
        - containerPort: 8545
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: cybersecurity
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: cybersecurity
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
  namespace: cybersecurity
spec:
  selector:
    app: blockchain
  ports:
  - protocol: TCP
    port: 8545
    targetPort: 8545
  type: ClusterIP
